In [2]:
import pandas as pd

In [4]:
T_data = pd.read_csv("12Months_Data.csv")

In [6]:
clean_d = T_data[T_data['average_sp'] <= T_data['avg_bill_value']]

In [7]:
grouped_data = T_data.groupby('sku_description')[['average_sp', 'avg_bill_value']].mean().reset_index()

In [8]:
grouped_data

,sku_description,average_sp,avg_bill_value
0,food-package-medium 450 ml pack of 10,60.000000,3796.220300
1,&Stirred bloody-mary-tomato-pepper 125 ml,50.000000,1528.749539
2,&Stirred classic-colada-mocktails-authentic-ri...,64.347826,1787.337017
3,&Stirred cocktail-mix-whisky-sour 100 ml Mono ...,120.000000,1232.066218
4,&Stirred cosmopolitan-cocktail-mix-refreshing-...,92.046429,2261.326788
...,...,...,...
78115,ÃUI red-velvet-eggless-cake-mix-luxe-edition-...,206.500000,1374.370629
78116,ÃUI rich-plum-cake-egg-based-holiday-edition-...,344.895825,2822.538762
78117,ÃUI rich-plum-cake-eggless-holiday-limited-ed...,335.693452,1562.274900
78118,ÃUI strawberry-chiffon-eggless-cake-mix-luxe-...,196.000000,1199.572200
78119,ÃUI triple-chocolate-cake-mix-signature-editi...,435.000000,3855.050000

In [9]:
grouped_data['percent_contribution'] = (grouped_data['average_sp'] / grouped_data['avg_bill_value']) * 100

In [10]:
grouped_data = grouped_data.sort_values(by='percent_contribution', ascending=False)

In [11]:
grouped_data

,sku_description,average_sp,avg_bill_value,percent_contribution
23687,Fresho leeks 1 kg,187.000000,1.815000e+02,103.030303
11615,Chicco baby-bottle-teat-medium-flow-2m 1 pc,299.000000,2.990000e+02,100.000000
11501,CherishX happy-birthday-golden-cake-topper-spe...,85.000000,8.500000e+01,100.000000
30465,Himalayan Organics probiotics-50-billion-capsu...,543.000000,5.430000e+02,100.000000
30467,Himalayan Organics retinol-facial-serum-with-h...,995.000000,9.950000e+02,100.000000
...,...,...,...,...
68628,Tata Sampann premium-pista-irani-roasted-and-s...,6.260000,1.702474e+05,0.003677
77420,bb Royal red-masoor-dal-whole-bulk-loose 30 kg...,89.080000,2.434911e+06,0.003658
73588,Vim extra-dishwash-bar-anti-bac-with-neem 300 g,18.185000,5.042146e+05,0.003607
27104,Grand tata-coffee-grand-pp 2.1 g,1.613469,8.069448e+04,0.001999
32627,Institutional crystal-salt 1 Kg,11.000000,1.005131e+06,0.001094

In [ ]:
###not a ggo idea